on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compiler:
    runs-on: ubuntu-latest
    container: rust:1.67
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release 
      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: |
            target
  releaser:
    runs-on: ubuntu-latest
    needs: compiler
    steps:
      - name: Download release-build
        uses: actions/download-artifact@v3
        with:
          name: release-build
      - run: find .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/noss/rusthello:latest
          cache-from: type=registry,ref=ghcr.io/noss/rusthello:buildcache
          cache-to: type=registry,ref=ghcr.io/noss/rusthello:buildcache,mode=max

